#!/usr/bin/env python3
"""Copy the same verified viewer to Pages and the Worker fallback host."""
from pathlib import Path
import json, shutil, mimetypes, hashlib, re

ROOT = Path(__file__).resolve().parents[1]
source = ROOT / 'app/src/main/assets'
target = ROOT / 'docs/app'
digest = hashlib.sha256()
for file in sorted(source.rglob('*')):
    if file.is_file() and file.name not in ('sw.js', 'schedule.json'):
        digest.update(file.relative_to(source).as_posix().encode()); digest.update(file.read_bytes())
sw = source / 'sw.js'
sw.write_text(re.sub(r"rgatu-ui-[^']+", 'rgatu-ui-' + digest.hexdigest()[:16], sw.read_text(), count=1))
shutil.copytree(source, target, dirs_exist_ok=True)
assets = {}
for file in source.rglob('*'):
    if not file.is_file() or file.name in ('schedule.json', 'LICENSE.txt'):
        continue
    relative = file.relative_to(source).as_posix()
    if file.suffix == '.png':
        # Worker serves PNGs from a base64 binding, decoded on request.
        import base64
        content = base64.b64encode(file.read_bytes()).decode()
        assets['/app/' + relative] = {'content': content, 'type': 'image/png', 'base64': True}
    else:
        assets['/app/' + relative] = {'content': file.read_text(), 'type': mimetypes.guess_type(relative)[0] or 'application/json'}
assets['/app/'] = assets['/app/index.html']
(ROOT / 'backend/src/assets.generated.js').write_text('// Generated by tools/prepare_web.py\nexport const assets = ' + json.dumps(assets, ensure_ascii=False, separators=(',', ':')) + ';\n')
print('Prepared Pages/PWA assets:', len(assets))
